# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  repositories:
    apache:
      repo: 'https://github.com/puppetlabs/puppetlabs-apache.git'
      ref: 'v5.4.0'
    apt:
      repo: 'https://github.com/puppetlabs/puppetlabs-apt.git'
      ref: 'v7.4.1'
    bareos:
      repo: 'https://github.com/voxpupuli/puppet-bareos.git'
      ref: 'b67e849be7219544c152567ea2aa300515ea3465'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
      ref: 'v6.2.0'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: 'v6.3.0'
